### ISSUE TITLE
 Problems using both the SD-XL-Base-1.0 model and/or the function pipe.unet = torch.compile(pipe.unet, mode="reduce-overhead", fullgraph=True)

### ISSUE THREAD

**Issue by linhduongtuan** [lyn-rgb/FreeU_Diffusers#5]
Hi,
Thank you for your work and wrapping it into Diffusers. However, I think it would be better if your reimplementation could work with the recent Diffusers version instead of version 0.19.3 or 0.21.2. So far, I have encountered problems using both the SD-XL-Base-1.0 model and/or the function pipe.unet = torch.compile(pipe.unet, mode="reduce-overhead", fullgraph=True). Thank you again for your time and assistance.
Linh

**Comment by neurowelt** [comment]
Would you be able to provide some tracebacks about what is happening?

**Comment by lyn-rgb** [comment]
Like neurowelt said, would you provide tracebacks when the error occurs?

**Comment by linhduongtuan** [comment]
Hi @neurowelt and @lyn-rgb 
Here are these tracebacks. Please find these in my attachments.
Here is a link to my Colab https://colab.research.google.com/drive/1Wsaf9x_hFijz6fgImFONwKClPCUexMaL?usp=sharing

My setting versions: 
Pytorch+CUDA versions = 2.0.1+cu118
Diffusers version = 0.22.0.dev0
Transformers version = 4.33.3
<img width="1371" alt="SD-XL-Base-1 0" src="https://github.com/lyn-rgb/FreeU_Diffusers/assets/22388092/fbfebe80-fc4f-4eaf-a56b-4c315844665a">
<img width="1131" alt="SD-2 1+torch compile(unet)" src="https://github.com/lyn-rgb/FreeU_Diffusers/assets/22388092/7e0adee7-3be1-4017-9856-9fa027dacab1">

**Comment by neurowelt** [comment]
Thanks for the Colab and tracebacks @linhduongtuan!

The first errors seems to be coming from using `StableDiffusionPipeline` for loading the XL model. I briefly remember encountering it a moment ago and [this stack post](https://stackoverflow.com/questions/76707159/diffusers-sdxl-typeerror-argument-of-type-nonetype-is-not-iterable) suggested using the `StableDiffusionXLPipeline` which works.

You can see that StableDiffusionPipeline class does not provide the `added_cond_kwargs` to unet, which then causes error:
```python
# predict the noise residual
noise_pred = self.unet(
    latent_model_input,
    t,
    encoder_hidden_states=prompt_embeds,
    cross_attention_kwargs=cross_attention_kwargs,
    return_dict=False,
)[0]
```

Meanwhile, in StableDiffusionXLPipeline it's defined properly (even if the kwargs themselves will be None):
```python
# predict the noise residual
added_cond_kwargs = {"text_embeds": add_text_embeds, "time_ids": add_time_ids}
noise_pred = self.unet(
    latent_model_input,
    t,
    encoder_hidden_states=prompt_embeds,
    cross_attention_kwargs=cross_attention_kwargs,
    added_cond_kwargs=added_cond_kwargs,
    return_dict=False,
)[0]
```

I'm trying to run the pipeline with `torch.compile` but am getting a slightly different error, will try to recreate the issue.

**Comment by neurowelt** [comment]
The second error seems to be caused by the `torch.compile` itself (see [pytorch#98161](https://github.com/pytorch/pytorch/issues/98161)).

**Comment by linhduongtuan** [comment]
Thank you, @neurowelt and @lyn-rgb for your time and assistance.
I will try following your suggestions.
Linh
